server:
  port: 8102
spring:
  application:
    name: erueka-client-b
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://wenbo:123456@127.0.0.1:8004/eureka/
